### ISSUE TITLE
ACE Worker Javascript not found

### ISSUE THREAD

**Issue by kkirsche** [masayuki0812/c3js.org#22]
On the example pages, it tries to `GET http://c3js.org/js/ace/worker-javascript.js` and returns `404 (Not Found)`.

If you replace the `worker-javascript.js` with `worker-javascript-f85eef4f.js` it works. This seems to be something in ACE that requires you to leave it as the original name of `worker-javascript.js`.

![screen shot 2015-01-20 at 9 54 19 am](https://cloud.githubusercontent.com/assets/947110/5819243/576038c2-a08a-11e4-98fa-29fa5d22d7b3.png)

**Comment by masayuki0812** [comment]
I updated to load ace scripts without hash and then it looks ok now. Thanks!
