### ISSUE TITLE
Text too long c3-legend-item-event / background does not wrap

### ISSUE THREAD

**Issue by alex2sony** [masayuki0812/c3js.org#24]
Hi, I am trying to make the Legend text to wrap by setting up some width limits. No matter what I tried I cannot figure out how to lessen the width of the ".c3-legend-item-event" where the text is so long that goes outside of my html. It is set to: legend: {position: 'inset'} and then I moved it toward the right of the graph but no way I can make the width shorter. Any help is appreciated. Thank you.

**Comment by masayuki0812** [comment]
Could you ask in https://groups.google.com/forum/#!forum/c3js ? Here is the issues for the web site (c3js.org), not the library (c3). Thanks!
