### ISSUE TITLE
Sub title in Donut Chart

### ISSUE THREAD

**Issue by jmoller** [masayuki0812/c3js.org#29]
Hello,

1) Is there any way to add a subtitle below the donut title? If so could you please advise on how to add it?

2) On the hover action in the donut chart, is it posible to display the actual number from the donut portion instead of the percentage?. 

Thank you,

**Comment by masayuki0812** [comment]
Could you ask in https://groups.google.com/forum/#!forum/c3js ? Here is the issues for the web site (c3js.org), not the library (c3). Thanks!
